name: Terraform CI

on:
  push:
    branches: [ "main", "feature/*" ]
    paths:
      - "environments/phase-2/**"
      - "modules/**"

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/phase-2

    steps:            
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
